#include "Gpt.h"


const Gpt_ConfigType gGpt_Configuration[GPT_CHANNELS_NUMBER] =
{
	{
		GPT_TIMER0,
		GPT_PRESCALE_256,
		GPT_NORMAL_MODE,
		GPT_INTERRUPT_ENABLE,
		0U   /* NOT IN CTC MODE */
	},
	
	{
		GPT_TIMER1,
		GPT_PRESCALE_1024,
		GPT_CTC_MODE,
		GPT_INTERRUPT_ENABLE,
		15625U     /* IN CTC MODE, THIS IS THE COMPARE VALUE */ 
	},
	
	{
		GPT_TIMER2,
		GPT_PRESCALE_256,
		GPT_NORMAL_MODE,
		GPT_INTERRUPT_ENABLE,
		0U   /* NOT IN CTC MODE */
	}
};